version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      DB_NAME: swe
      DB_USER: postgres
      DB_PASSWORD: yV5pqpDRvDN6rDn
      DB_HOST: swe.cc1obugfex3a.us-east-2.rds.amazonaws.com
      DJ_SECRET_KEY: '*gm0r5nh_#styeqjvke@mz^u=*4&n68_e_f!r12rpzpn(c8^_7'
      TW_SECRET_ID: 'wlrTcc1yCtTmPxt10SgzYXp2q'
      TW_SECRET_KEY: 'ZHLAv5jIttoL6qnyZUcM8coJIgCMJYqREL5lV1HmFhLLL7sha8'
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start